name: Simple Deployment Workflow

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Dev
        run: |
          echo "Simulating deployment to Dev environment..."

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Staging
        run: |
          echo "Simulating deployment to Staging environment..."

  deploy-production:
    needs: deploy-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Production
        run: |
          echo "Simulating deployment to Production environment..."
